---
- hosts: webservers
  vars:
    http_port: 3000
  remote_user: ec2-user
  tasks:
  - name: install docker
    yum: pkg=docker state=latest
  - name: install docker-py
    pip: name=docker-py
    become: yes
    become_method: sudo
  - name: migrate database
    docker:
      image: pschorf/tiling
      pull: always
      command: java -cp /var/web/tiling.jar tiling.db.migrate
      volumes:
      - /ecs/tiling:/etc/tiling
      
